#################################################################
## Light Group
#################################################################

- platform: group
  name: Living Room
  entities:
    - light.living_room_dimmer
    - light.living_room_fireplace_dimmer
    - light.living_room_lamp

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_dimmer

- platform: group
  name: Media Room
  entities:
    - light.theater_bar
    - light.theater_seating

- platform: group
  name: Laundry
  entities:
    - light.laundry_room

- platform: group
  name: Backyard
  entities:
    - light.living_room_exterior

# - platform: group
#   name: Front Yard
#   entities:
#     - switch.shop_driveway_exterior_lights

- platform: group
  name: Master Bedroom
  entities:
    - light.master_bedroom_fan_light

- platform: group
  name: Master Bathroom
  entities:
    - light.master_bathroom
