<<: !include ../secrets.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

api:

ota:

web_server:
  port: 80

sensor:
  - platform: uptime
    name: $upper_devicename Uptime

  - platform: wifi_signal
    name: $upper_devicename WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: status
    name: $upper_devicename Status
