substitutions:
  devicename: irrigation_controller
  upper_devicename: Irrigation Controller

<<: !include .common.yaml

api:
  services:
    - service: start_effect
      variables:
        my_brightness: int
        my_effect: string
      then:
        - light.turn_on:
            id: my_light
            brightness: !lambda 'return my_brightness;'
            effect: !lambda 'return my_effect;'

switch:
  - name: Irrigation Zone 1
    platform: gpio
    pin:
      number: D0
      inverted: true
    id: zone_1
    # Interlock to prevent more than one high flow zone active at a time
    interlock: &interlock_group [zone_1, zone_2, zone_4]
    # Set automatic timeout 10 minutes
    on_turn_on:
      then:
        - delay: 15min
        - switch.turn_off: zone_1

  - name: Irrigation Zone 2
    platform: gpio
    pin:
      number: D1
      inverted: true
    id: zone_2
    interlock: *interlock_group
    on_turn_on:
      then:
        - delay: 15min
        - switch.turn_off: zone_2

  - name: Irrigation Zone 3
    platform: gpio
    pin:
      number: D2
      inverted: true
    id: zone_3
    on_turn_on:
      then:
        - delay: 30min
        - switch.turn_off: zone_3

  - name: Irrigation Zone 4
    platform: gpio
    pin:
      number: D5
      inverted: true
    id: zone_4
    interlock: *interlock_group
    on_turn_on:
      then:
        - delay: 15min
        - switch.turn_off: zone_4
