substitutions:
  devicename: pool_controller
  upper_devicename: Pool Pump Controller

<<: !include .common.yaml

sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      # - 1876.8Ohm -> 28.3333째C # 29.4
      - 1667.7Ohm -> 29.4째C # 29.4
      - 2119.6Ohm -> 20째C
      - 2626.9Ohm -> 10째C
    name: Pool Water Temperature
    icon: mdi:coolant-temperature
    # filters:
    #   - median:

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor

  - platform: adc
    id: source_sensor
    pin: A0
    update_interval: never

switch:
  - platform: gpio
    pin: D0
    id: ntc_vcc
  - platform: gpio
    id: pump
    name: Pool Pump Power
    pin:
      number: GPIO0
      inverted: False
    icon: mdi:water-pump
    restore_mode: ALWAYS_OFF

interval:
  - interval: 30s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc
