input_number:
  pool_freeze_protection_temp:
    name: Pool Freeze Protection Temp
    min: 32
    max: 40
    step: 1
    mode: box
    unit_of_measurement: "°F"
    icon: mdi:snowflake-alert
  pool_freeze_protection_temp_differential:
    name: Pool Freeze Protection Temp Differential
    min: 1
    max: 5
    step: 1
    mode: box
    unit_of_measurement: "°F"

input_boolean:
  pool_winter_schedule:
    name: Pool Winter Schedule

sensor:
  - platform: history_stats
    name: Daily Pool Pump Runtime
    entity_id: switch.pool_pump_power
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: template
    sensors:
      daily_pool_pump_power_consumption:
        friendly_name: "Daily Pool Pump Power Comsumption"
        unit_of_measurement: "kWh"
        value_template: '{{ (states("sensor.daily_pool_pump_runtime")|float * 1.8 )| round(2) }}'

automation:
  - alias: Pool Pump On
    trigger:
      - at: "05:00:00"
        platform: time
      - at: "20:00:00"
        platform: time
      - platform: template
        value_template: >-
          {{ states('sensor.my_weather_station_temp')|float <= states('input_number.pool_freeze_protection_temp')|float }}
        for:
          minutes: 1
    action:
      - service: switch.turn_on
        entity_id: switch.pool_pump_power

  - alias: Pool Pump Off
    trigger:
      - at: "08:00:00"
        platform: time
      - at: "23:00:00"
        platform: time
    condition:
      - condition: template
        value_template: >-
          {{ states('sensor.my_weather_station_temp')|float >= states('input_number.pool_freeze_protection_temp')|float }}
    action:
      - service: switch.turn_off
        entity_id: switch.pool_pump_power
